name: main
on:
  push:
    branches:
      - main

jobs:
  Install:
    uses: ./.github/workflows/install.yml

  lint:
    runs-on: ubuntu-latest
    needs: Install
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Eslint test
        run: yarn lint:check
